# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zr < Formula
  desc "Zuora CLI - Work with Zuora from the command line"
  homepage "https://github.com/matsuzj/zuora-cli"
  version "0.7.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/matsuzj/zuora-cli/releases/download/v0.7.0/zr_0.7.0_darwin_amd64.tar.gz"
      sha256 "1287010c07017701953e3aee8518ab703738351fab4d3e9f7fe45e8e5c599a50"

      define_method(:install) do
        bin.install "zr"
        bash_completion.install "completions/zr.bash" => "zr"
        zsh_completion.install "completions/zr.zsh" => "_zr"
        fish_completion.install "completions/zr.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/matsuzj/zuora-cli/releases/download/v0.7.0/zr_0.7.0_darwin_arm64.tar.gz"
      sha256 "6fba0e44f577a4a832f3b00c989b652db9e4b9d180a41e294a4b7d3896d1c888"

      define_method(:install) do
        bin.install "zr"
        bash_completion.install "completions/zr.bash" => "zr"
        zsh_completion.install "completions/zr.zsh" => "_zr"
        fish_completion.install "completions/zr.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/matsuzj/zuora-cli/releases/download/v0.7.0/zr_0.7.0_linux_amd64.tar.gz"
      sha256 "ae0d8d483faba9abc984c2c0691daa7a7c41c6f0812fce0bfc78b3047ab3167f"
      define_method(:install) do
        bin.install "zr"
        bash_completion.install "completions/zr.bash" => "zr"
        zsh_completion.install "completions/zr.zsh" => "_zr"
        fish_completion.install "completions/zr.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/matsuzj/zuora-cli/releases/download/v0.7.0/zr_0.7.0_linux_arm64.tar.gz"
      sha256 "fd6a7c87b93c6d7b150db9e412b67809b9180cd0acb3bab1e35880a8b646534d"
      define_method(:install) do
        bin.install "zr"
        bash_completion.install "completions/zr.bash" => "zr"
        zsh_completion.install "completions/zr.zsh" => "_zr"
        fish_completion.install "completions/zr.fish"
      end
    end
  end

  test do
    system "#{bin}/zr", "version"
  end
end
