# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zr < Formula
  desc "Zuora CLI - Work with Zuora from the command line"
  homepage "https://github.com/matsuzj/zuora-cli"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/matsuzj/zuora-cli/releases/download/v0.4.0/zr_0.4.0_darwin_amd64.tar.gz"
      sha256 "0e50602881fa228153c6b6339815b131e777cbf9899cb477bb4cf65cf57a2df6"

      define_method(:install) do
        bin.install "zr"
        bash_completion.install "completions/zr.bash" => "zr"
        zsh_completion.install "completions/zr.zsh" => "_zr"
        fish_completion.install "completions/zr.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/matsuzj/zuora-cli/releases/download/v0.4.0/zr_0.4.0_darwin_arm64.tar.gz"
      sha256 "2e4a37c7c24909610d4834b530a58828ab79fca49e8fe6fc9ed7e44ab3cf3119"

      define_method(:install) do
        bin.install "zr"
        bash_completion.install "completions/zr.bash" => "zr"
        zsh_completion.install "completions/zr.zsh" => "_zr"
        fish_completion.install "completions/zr.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/matsuzj/zuora-cli/releases/download/v0.4.0/zr_0.4.0_linux_amd64.tar.gz"
      sha256 "31dca48166efbfc3ba50db9a0de2d3623362165d13813e6839cfdf17db70f3f2"
      define_method(:install) do
        bin.install "zr"
        bash_completion.install "completions/zr.bash" => "zr"
        zsh_completion.install "completions/zr.zsh" => "_zr"
        fish_completion.install "completions/zr.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/matsuzj/zuora-cli/releases/download/v0.4.0/zr_0.4.0_linux_arm64.tar.gz"
      sha256 "ac8de42ad88a8cbdb6c7902115def5c33ba910decbe5fd3899b2d98b59441d81"
      define_method(:install) do
        bin.install "zr"
        bash_completion.install "completions/zr.bash" => "zr"
        zsh_completion.install "completions/zr.zsh" => "_zr"
        fish_completion.install "completions/zr.fish"
      end
    end
  end

  test do
    system "#{bin}/zr", "version"
  end
end
