# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zr < Formula
  desc "Zuora CLI - Work with Zuora from the command line"
  homepage "https://github.com/matsuzj/zuora-cli"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/matsuzj/zuora-cli/releases/download/v0.2.0/zr_0.2.0_darwin_amd64.tar.gz"
      sha256 "4bc6def37f4ff77987bc7b53971da6c81370471a9dd6ab763ede984f6846c3bc"

      define_method(:install) do
        bin.install "zr"
        bash_completion.install "completions/zr.bash" => "zr"
        zsh_completion.install "completions/zr.zsh" => "_zr"
        fish_completion.install "completions/zr.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/matsuzj/zuora-cli/releases/download/v0.2.0/zr_0.2.0_darwin_arm64.tar.gz"
      sha256 "bdf76869cf26fec757f4bf0a57ef4cf7b6c6583b3673b6c00ec303b653634d41"

      define_method(:install) do
        bin.install "zr"
        bash_completion.install "completions/zr.bash" => "zr"
        zsh_completion.install "completions/zr.zsh" => "_zr"
        fish_completion.install "completions/zr.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/matsuzj/zuora-cli/releases/download/v0.2.0/zr_0.2.0_linux_amd64.tar.gz"
      sha256 "5983bdeecf98218b979298a073b4e836530480fc7202e7293946b899debac671"
      define_method(:install) do
        bin.install "zr"
        bash_completion.install "completions/zr.bash" => "zr"
        zsh_completion.install "completions/zr.zsh" => "_zr"
        fish_completion.install "completions/zr.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/matsuzj/zuora-cli/releases/download/v0.2.0/zr_0.2.0_linux_arm64.tar.gz"
      sha256 "a022788558ef76fa46ffae5a9da6f1dcfa31865a0148499b96f568827f401eaf"
      define_method(:install) do
        bin.install "zr"
        bash_completion.install "completions/zr.bash" => "zr"
        zsh_completion.install "completions/zr.zsh" => "_zr"
        fish_completion.install "completions/zr.fish"
      end
    end
  end

  test do
    system "#{bin}/zr", "version"
  end
end
